namespace PowerClock
{
    [default_interface]
    runtimeclass ColorsWindow : Microsoft.UI.Xaml.Window
    {
        ColorsWindow();

        event Windows.Foundation.TypedEventHandler<ColorsWindow, BackdropControllerType> BackdropChanged;
    };

    enum BackdropControllerType
    {
        None,
        AcrylicBackdrop,
        MicaBackdrop
    };
}
